Epoch 1/5:   0%|                                                                                                                                              | 0/283 [00:00<?, ?img/s]
✅ 변환된 마스크 값 확인: tensor([0, 1, 2], device='cuda:0')
Traceback (most recent call last):
  File "c:\Users\AMI-DEEP3\Desktop\younguk\Pytorch-UNet-master\Pytorch-UNet-master\train.py", line 144, in <module>
    train_model(
  File "c:\Users\AMI-DEEP3\Desktop\younguk\Pytorch-UNet-master\Pytorch-UNet-master\train.py", line 96, in train_model
    F.one_hot(true_masks, model.n_classes).permute(0, 3, 1, 2).float(),
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
